---
title: "JHU_COVID-19_MD"
author: "Jonah Pool"
date: "5/26/2020"
output:
  html_document: default
  word_document: default
  pdf_document: default
---
```{r setup, include=FALSE}
library(tidyverse)
library(magrittr)
library(ggplot2)
library(flextable)
library(lubridate)
library(DescTools)
library(pwr)
library(sjPlot)
library(webshot)
library(scales)

library(maps)
library(plotly)
library(kableExtra)
library(knitr)
```

Constants
```{r}
yd <- today()  - ddays(1)
td <- today()


day <- yd
MichiganRiots<- seq(ymd("2020-05-26"), ymd("2020-06-1"), by = 1)
exclude = c("")
# date for daily data release
a <- as.character(ymd(day))
b <- str_split(a, "-")
c1 <- as.character(b[[1]][2])
c2 <- as.character(b[[1]][3]) 
c3 <- as.character(b[[1]][1])
d_lookup_str <- str_c(c1, c2, c3, sep = "-")

sinceMarch16 <- seq(date("2020-03-16"), day, by=1)

last30 <- seq(td-30, td, by=1)
last21 <- seq(td-21, td, by=1)
last14 <- seq(td-14, td, by=1)
last7 <- seq(td-7, td, by=1)



bold.14.text <- element_text(face = "bold", size = 12)

red.fill.5 <- c("#bf080e","#bf080e","#bf080e","#bf080e","#bf080e")
blue.fill.5 <- c("#0016bd","#0016bd","#0016bd","#0016bd","#0016bd")

red.fill.10 <- c("#bf080e","#bf080e","#bf080e","#bf080e","#bf080e","#bf080e","#bf080e","#bf080e","#bf080e","#bf080e")
blue.fill.10 <- c("#0016bd","#0016bd","#0016bd","#0016bd","#0016bd","#0016bd","#0016bd","#0016bd","#0016bd","#0016bd")

x.limit.march15 <- seq(ymd("2020-03-15"), day, by=1)

#annotation.moving.average <- annotate(geom = "text", x = xrange[1], y = yrange[2], label = paste(strwrap("Note: 5 Day Moving Average", 40), collapse = "\n"), hjust = 0, vjust = 1, size = 4)

pq <- theme(text = bold.14.text) +
  #theme(axis.ticks = element_blank()) +
  theme(panel.border = element_rect(colour = "black", fill=NA, size=2))
jhu_caption <- labs(caption="Data Source: Johns Hopkins University CSSE")
```

Functions
```{r}
ma <- function(arr, n=5){
  res = arr
  for(i in n:length(arr)){
    res[i] = mean(arr[(i-n+1):i])
  }
  res
}

movingAverage <- function(x, n=7, centered=FALSE) {
    
    if (centered) {
        before <- floor  ((n-1)/2)
        after  <- ceiling((n-1)/2)
    } else {
        before <- n-1
        after  <- 0
    }

    # Track the sum and count of number of non-NA items
    s     <- rep(0, length(x))
    count <- rep(0, length(x))
    
    # Add the centered data 
    new <- x
    # Add to count list wherever there isn't a 
    count <- count + !is.na(new)
    # Now replace NA_s with 0_s and add to total
    new[is.na(new)] <- 0
    s <- s + new
    
    # Add the data from before
    i <- 1
    while (i <= before) {
        # This is the vector with offset values to add
        new   <- c(rep(NA, i), x[1:(length(x)-i)])

        count <- count + !is.na(new)
        new[is.na(new)] <- 0
        s <- s + new
        
        i <- i+1
    }

    # Add the data from after
    i <- 1
    while (i <= after) {
        # This is the vector with offset values to add
        new   <- c(x[(i+1):length(x)], rep(NA, i))
       
        count <- count + !is.na(new)
        new[is.na(new)] <- 0
        s <- s + new
        
        i <- i+1
    }
    
    # return sum divided by count
    s/count
}

bar_chart_ts <- function(df, y, custom.fill = blue.fill.10, lab.title, y.lim = max(y)) {
  plot <- ggplot(df, aes(x = date, y = y, fill = "")) + 
    geom_col() +
    scale_fill_manual(values = custom.fill) +
    labs(y = "", title = lab.title, x = "Date") +
    theme(legend.position = "none") +
    ylim(0,y.lim) +
    pq
  plot
}

line_chart_ts <- function(df, y, custom.fill = blue.fill.10, lab.title, y.lim = max(y)) {
  plot <- ggplot(df, aes(x = date, y = y, color = "", fill = "")) + 
    geom_line(size = 1.2) +
    scale_fill_manual(values = custom.fill) +
    scale_color_manual(values = custom.fill)+
    labs(y = "", title = lab.title, x = "Date") +
    theme(legend.position = "none") +
    ylim(0,y.lim) +
    pq
  plot
}

line_chart_ma_ts <- function(df, y, custom.fill = blue.fill.10, lab.title, y.lim = max(y)) {
  plot <- ggplot(df, aes(x = date, y = y, color = "", fill = "")) + 
    geom_smooth(size = 1.2) +
    scale_fill_manual(values = custom.fill) +
    scale_color_manual(values = custom.fill)+
    labs(y = "", title = lab.title, x = "Date") +
    theme(legend.position = "none") +
    ylim(0,y.lim) +
    pq
  plot
}

```

Load Johns Hopkins Univ. CSSE Data
```{r}
ts_date_count <- today() - ymd(20200122)

daily_fname <- str_c("../COVID-19/csse_covid_19_data/csse_covid_19_daily_reports_us/", d_lookup_str, ".csv")
csse_today <- read_csv(daily_fname, col_types = "ccTddddddddddddcdd")
csse_confirmed_us_ts <- read_csv("../COVID-19/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_US.csv",
                                 col_types=str_c('cccddcccddc', 
                                 str_c(rep("i", times=ts_date_count), collapse=""))
                                 )

csse_deaths_us_ts <- read_csv("../COVID-19/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_US.csv", 
                              col_types=str_c('cccddcccddc', 
                              str_c(rep("i", times=ts_date_count+1), collapse=""))
                              )
uid <- read_csv("../COVID-19/csse_covid_19_data/UID_ISO_FIPS_LookUp_Table.csv", col_types = "cccddcccddci")
daily_updates_ts <- read_csv("daily_updates_ts_us.csv", col_types="ccDdTdcdddddddddddddd")
```

Filter US ID Values
```{r}

us_uid <- uid %>% 
  filter(code3 %in% c(16, 316, 580, 850, 630, 840)) %>%
  select(UID, Province_State, Combined_Key, Population) %>% 
  arrange(UID)
states <- c(us_uid$Province_State[1:4], us_uid$Province_State[6:57])
states_uid <-seq(84000001, 84000056, by = 1)
uid_states <- us_uid %>% 
  filter(UID %in% c(16, 316, 580, 850, 630, seq(84000001, 84000056, by = 1)))

```

Maryland Data
```{r}
md_cases_ts <- csse_confirmed_us_ts %>%
  select(-Lat, -Long_, -FIPS) %>%
  filter(Province_State %in% us_uid$Province_State) %>% 
  filter(!(is.na(Admin2))) %>% 
  filter(Province_State %in% c("Maryland")) %>%
  group_by(UID) %>%
  pivot_longer(`1/22/20`:last_col(), names_to = "date", values_to = "cases") %>% 
  ungroup()



md_cases_ts %<>%
  select(-iso2, -iso3, -code3, -Province_State) %>% 
  inner_join(us_uid, by = c("UID", "Combined_Key")) %>%
  mutate(date = mdy(date)) %>%
  arrange(Admin2) %>%
  group_by(Admin2) %>% 
  mutate(cases_per_hundred_thousand = round((cases / Population * 100000), 1), cases_delta=cases-lag(cases), cases_relative = cases_delta / lag(cases)) %>% 
  ungroup()

md_cases_ts %<>%
  mutate(cases_delta = case_when(
    is.na(cases_delta) ~ as.double(cases),
    TRUE ~ as.double(cases) - as.double(lag(cases))
  ), cases_delta_per_hundred_thousand = round((100000 * cases_delta / Population), 2), cases_delta_ma = movingAverage(cases_delta), cases_delta_ma_per_hundred_thousand = movingAverage(cases_delta_per_hundred_thousand),
  cases_relative = case_when(
    is.na(cases_relative) ~ 0,
    cases_relative == Inf ~ 1,
    TRUE ~ cases_delta / lag(cases)), cases_perc = round((100 * cases_relative), 3), cases_perc_ma = movingAverage(cases_perc)) %>%
  ungroup() %>% 
  filter(!(date %in% exclude)) %>% 
  rename(state = Province_State) %>% 
  rename(County = Admin2) %>% 
  filter(date %in% sinceMarch16)

top5counties <- md_cases_ts %>% 
  filter(date == day) %>% 
  top_n(5, cases)

md_deaths_ts <- csse_deaths_us_ts %>%
  select(-Lat, -Long_, -FIPS) %>%
  filter(Province_State %in% us_uid$Province_State) %>% 
  #filter(!(is.na(Admin2))) %>% 
  filter(Province_State %in% c("Maryland")) %>%
  group_by(UID) %>%
  pivot_longer(`1/22/20`:last_col(), names_to = "date", values_to = "deaths") %>% 
  ungroup()
  

md_deaths_ts %<>% 
  select(-iso2, -iso3, -code3, -Province_State) %>% 
  group_by(date) %>% 
  inner_join(us_uid, by = c("UID", "Combined_Key", "Population")) %>%
  ungroup() %>% 
  mutate(date = mdy(date)) %>%
  arrange(Admin2) %>%
  group_by(Admin2) %>% 
  mutate(deaths_per_hundred_thousand = round((100000 * deaths / Population), 2), deaths_delta = deaths - lag(deaths), deaths_relative = deaths_delta / lag(deaths)) %>% 
  ungroup()

md_deaths_ts %<>%
  mutate(deaths_delta = case_when(
    is.na(deaths_delta) ~ as.double(deaths),
    #deaths_delta < 0 ~ 0,
    TRUE ~ as.double(deaths) - as.double(lag(deaths))
  ), deaths_delta_per_hundred_thousand = round((100000 * deaths_delta / Population), 2), deaths_delta_ma = movingAverage(deaths_delta), deaths_delta_ma_per_hundred_thousand = movingAverage(deaths_delta_per_hundred_thousand),
  deaths_relative = case_when(
    is.na(deaths_relative) ~ 0,
    deaths_relative == Inf ~ 1,
    TRUE ~ deaths_delta / lag(deaths)), deaths_perc = round((100 * deaths_relative), 3), deaths_perc_ma = movingAverage(deaths_perc)) %>% 
  ungroup() %>% 
  filter(!(date %in% exclude)) %>% 
  rename(state = Province_State) %>% 
  rename(County = Admin2) %>% 
  filter(date %in% sinceMarch16)
  
md_combined_ts <- md_cases_ts %>% 
  full_join(md_deaths_ts) %>% 
  filter(date %in% sinceMarch16)
md_combined_ts[is.na(md_combined_ts)] <- as.double(0)
md_combined_ts[md_combined_ts == Inf]<- as.double(100)
```

```{r}
two_week_sum <- md_combined_ts %>% 
  group_by(County) %>%
  arrange(date) %>% 
  mutate(week_num = week(date)) %>% 
  ungroup() %>% 
  group_by(week_num, County) %>% 
  filter(date == max(date)) %>% 
  ungroup() %>% 
  group_by(week_num) %>% 
  summarize(date=date, week_num=week_num, County = County, Combined_Key = Combined_Key, cases = cases, deaths = deaths) %>% 
  #select(date, week_num, County, Combined_Key, cases, deaths) %>% 
  ungroup() %>% 
  filter((week_num %% 2) == (max(week_num) %% 2)) %>% 
  group_by(County) %>% 
  mutate(cases_delta_tw = cases - lag(cases), 
         deaths_delta_tw = deaths - lag(deaths), 
         cases_relative_tw = 100 * (cases - lag(cases)) / lag(cases), 
         deaths_relative_tw = 100 * (deaths - lag(deaths)) / lag(deaths),
         cases_spiking = cases_relative_tw > lag(cases_relative_tw),
         deaths_spiking = deaths_relative_tw > lag(deaths_relative_tw)) %>% 
  #mutate(deaths_dir = (cases)) %>% 
  ungroup() %>% 
  filter(County == "Montgomery") %>% 
  select(-week_num)

two_week_sum

priority_counties <- c("Montgomery", "Frederick", "Prince George's", "Anne Arundel")

md_priority_ts <- md_combined_ts %>% 
  filter(County %in% priority_counties) %>% 
  group_by(County) %>% 
  arrange(date) %>%
  ungroup()
```

```{r}
xrange <-range(md_priority_ts$date)
yrange <- range(md_priority_ts$cases_delta_ma_per_hundred_thousand)

p11 <- ggplot(md_priority_ts, aes(x = date, y = cases_per_hundred_thousand, color = County)) +
  #geom_col(position = "stack", aes(group=County), size = 1.2) +
  geom_line(aes(group=County), size = 1.2) + 
  labs(y = "", title = "Daily New Cases in Maryland by County", x = "Date") + 
  theme(legend.position = "bottom") + 
  annotate(geom = "text", x = xrange[1], y = yrange[2], label = paste(strwrap("Note: 7 Day Moving Average", 40), collapse = "\n"), hjust = 0, vjust = 0, size = 4)+ 
  #facet_wrap("County") +
  pq+jhu_caption
p11
```

```{r}
sum_deaths <- md_priority_ts %>% ungroup() %>% group_by(date) %>% select(date, deaths_delta_ma_per_hundred_thousand) %>% mutate(deaths_delta = sum(deaths_delta_ma_per_hundred_thousand))
max_deaths <- max(sum_deaths$deaths_delta_ma_per_hundred_thousand)

xrange <-range(md_priority_ts$date)
yrange <- range(0, max_deaths)

p12 <- md_priority_ts %>% ggplot(aes(group = County, x = date, y = deaths_delta_ma_per_hundred_thousand, color = County)) +
  #geom_col(position = "stack", aes(group=County), size = 1.2) +
  geom_line(aes(group=County), size = 0.8) + 
  labs(y = "", title = "Daily Deaths in Maryland by County", x = "Date") + 
  theme(legend.position = "bottom") + 
  #xlim(date("2020-03-01"),date("2020-07-15"))+
  annotate(geom = "text", x = xrange[2], y = yrange[2], label = paste(strwrap("Note: 7 Day Moving Average", 40), collapse = "\n"), hjust = 1, vjust = 1, size = 4) + 
  pq+jhu_caption+
  facet_wrap("County")
p12
```


```{r}
md_sum_ts <- md_combined_ts %>% 
  arrange(date) %>% 
  group_by(date) %>% 
  summarise(population = uid_states$Population[26], cases = sum(cases), cases_it = cases / 1000, cases_delta = sum(cases_delta), cases_per_hundred_thousand = 100000 * cases / population, cases_perc = 100 * cases_delta / lag(cases), deaths = sum(deaths), deaths_delta = sum(deaths_delta), deaths_perc = as.double(100 * deaths_delta / lag(deaths)), deaths_per_hundred_thousand = 100000 * deaths / population)

md_sum_ts %<>% 
  mutate(lag_cases = as.double(lag(cases)), relative = cases_delta / lag_cases, cases_delta_ma = movingAverage(cases_delta),
  cases_perc = case_when(
    cases_perc == Inf ~ 100,
    TRUE ~ (100 * sum(cases_delta) / lag_cases)), cases_dir = (cases_delta_ma < lag(cases_delta_ma)),
  cases_perc_ma = movingAverage(cases_perc),
  lag_deaths = as.double(lag(deaths)), relative = deaths_delta / lag_deaths, deaths_delta_ma = movingAverage(deaths_delta),
  deaths_perc = case_when(
    deaths_perc == Inf ~ 100,
    TRUE ~ (100 * deaths_delta / lag_deaths)), deaths_dir = (deaths_delta_ma <= lag(deaths_delta_ma)),
  deaths_perc_ma = movingAverage(deaths_perc)) %>% 
  ungroup()
md_sum_ts[is.na(md_sum_ts)] <- as.double(0)
md_sum_ts[md_sum_ts == Inf]<- as.double(100)
md_sum_ts %<>%
  mutate(cases_dir = factor(md_sum_ts$cases_dir, labels = c("red", "green")))
md_sum_ts_last30 <- md_sum_ts %>% 
  filter(date %in% sinceMarch16)
```



```{r}
md_sum_cases_today <- md_sum_ts_last30 %>% 
  select(date, cases, cases_delta, cases_per_hundred_thousand, cases_delta_ma) %>% 
  tail(1)
md_sum_cases_today
```

```{r}
md_sum_deaths_today <- md_sum_ts_last30 %>% 
  select(date, deaths, deaths_delta, deaths_per_hundred_thousand, deaths_delta_ma) %>% 
  tail(1)
md_sum_deaths_today
```

```{r}
mortality_rate <- md_sum_deaths_today$deaths / md_sum_cases_today$cases
mortality_rate * 100
```


```{r, message=FALSE, warning=FALSE}
xrange <-range(md_sum_ts_last30$date)
yrange <- range(md_sum_ts_last30$cases_delta)

cases_today_md <- round(md_sum_cases_today$cases_delta_ma[1], 0)
cases_last_week_md <- md_sum_ts$cases_delta_ma[nrow(md_sum_ts)-7]

perc_change_md <- round(((cases_today_md - cases_last_week_md)/cases_last_week_md),3)*100
perc_change_txt <- function(x){
  if (x > 0) {
    out_text <- paste("+", as.character(abs(x)))
    out_text
  }
  else {
    out_text <- paste("-", as.character(abs(x)))
    out_text
  }
}

cases_text_md <- paste(as.character(today()),"\n","___24 Hours___\nNew Cases: +", as.character(cases_today_md), "\nPercent Change (7 Days): ", perc_change_txt(perc_change_md), "%\nData Source: Johns Hopkins University CSSE")

md_p1 <- md_sum_ts_last30 %>% ggplot() + 
    geom_rect(md_sum_ts_last30, x=md_sum_ts_last30$date, y = md_sum_ts_last30$cases_delta_ma, mapping = aes(xmin = lag(date), xmax = date, fill = cases_dir), ymin = 0, ymax = Inf, alpha = 0.3) + 
    geom_line(aes(x = date, y = cases_delta_ma, color = ""), size = 1.2) +
    geom_point(aes(x=date, y=cases_delta, color=""), alpha = 0.7)+
    scale_color_manual(values = "black")+
    scale_fill_manual(values = c("blue", "yellow"))+
    labs(y = "", title = "Daily New Cases in Maryland", x = "Date") +
    theme(legend.position = "none") +
    pq+
    ylim(0,max(md_sum_ts_last30$cases_delta_ma))+
    annotate(geom = "text", x = xrange[1], y = yrange[2], label = paste("Note: 7 Day Moving Average", collapse = "\n"), hjust = 0, vjust = 1, size = 4)+
  labs(caption=cases_text_md, vjust= 0)
md_p1
```


```{r warning = FALSE}
xrange <-range(md_sum_ts_last30$date)
yrange <- range(md_sum_ts_last30$deaths_delta)


deaths_today_md <- round(md_sum_deaths_today$deaths_delta_ma[1],0)
deaths_last_week_md <- md_sum_ts$deaths_delta_ma[nrow(md_sum_ts)-7]

perc_deaths_md <- round(((deaths_today_md - deaths_last_week_md)/deaths_last_week_md),3)*100
deaths_text_md <- paste(as.character(today()),"\n","___24 Hours___\nDeaths Today: +", as.character(deaths_today_md), "\nPercent Change (7 Days): ", perc_change_txt(perc_deaths_md), "%\nData Source: Johns Hopkins University CSSE")

md_p2 <- md_sum_ts_last30 %>% ggplot() + 
    geom_rect(md_sum_ts_last30, x=md_sum_ts_last30$date, y = md_sum_ts_last30$deaths_delta, mapping = aes(xmin = lag(date), xmax = date, fill = deaths_dir), ymin = 0, ymax = Inf, alpha = 0.3) + 
    geom_point(aes(x = date, y = deaths_delta, color = ""), alpha = 0.7)+
    geom_line(aes(x = date, y = deaths_delta_ma), size = 1.2, alpha = 0.9) +
    scale_fill_manual(values = c("red", "green", "red"))+
    scale_color_manual(values = c("black", "black", "black"))+
    labs(y = "", title = "Daily Deaths in Maryland", x = "Date") +
    theme(legend.position = "none") +
    pq + 
    ylim(0,max(md_sum_ts_last30$deaths_delta))+
    annotate(geom = "text", x = xrange[1], y = yrange[2], label = paste("Note: 7 Day Moving Average", collapse = "\n"), hjust = 0, vjust = 1, size = 4)+jhu_caption+
  labs(caption=deaths_text_md, vjust= 1)
md_p2

```

Montgomery County Data

```{r}
montgomery_ts <- md_combined_ts %>% 
  filter(County == "Montgomery") %>% 
  mutate(cases_dir = (cases_delta_ma <= lag(cases_delta_ma)), deaths_dir = (deaths_delta_ma <= lag(deaths_delta_ma))) %>% 
  filter(date %in% sinceMarch16)
  
```

```{r message=FALSE, warning=FALSE}
xrange <-range(montgomery_ts$date)
yrange <- range(montgomery_ts$cases_delta)

cases_today_moco <- round(montgomery_ts$cases_delta_ma[nrow(montgomery_ts)],0)
cases_last_week_moco <- montgomery_ts$cases_delta_ma[nrow(montgomery_ts)-7]

perc_change_moco <- round(((cases_today_moco - cases_last_week_moco)/cases_last_week_moco),3)*100
cases_text_moco <- paste(as.character(today()),"\n","___24 Hours___\nNew Cases: +", as.character(cases_today_moco), "\nPercent Change (7 Days): ", perc_change_txt(perc_change_moco), "%\nData Source: Johns Hopkins University CSSE")

mont_p1 <- montgomery_ts %>% ggplot() + 
    geom_rect(montgomery_ts, x=montgomery_ts$date, y = montgomery_ts$cases_delta, mapping = aes(xmin = lag(date), xmax = date, fill = cases_dir), ymin = 0, ymax = Inf, alpha = 0.3) + 
    geom_point(aes(x=date, y=cases_delta, color=""), alpha = 0.7)+  
    geom_line(aes(x = date, y = cases_delta_ma, color = ""), size = 1.2, alpha = 0.9) +
    scale_color_manual(values = "black", "black")+
    scale_fill_manual(values = c("blue", "yellow"))+
    labs(y = "", title = "Daily New Cases in Montgomery County", x = "Date") +
    theme(legend.position = "none") +
    pq+
    ylim(0,max(montgomery_ts$cases_delta))+
    annotate(geom = "text", x = xrange[1], y = yrange[2], label = paste("Note: 7 Day Moving Average", collapse = "\n"), hjust = 0, vjust = 1, size = 4)+jhu_caption+
    labs(caption=cases_text_moco, vjust= 1)
mont_p1
```

```{r warning = FALSE}
xrange <-range(montgomery_ts$date)
yrange <- range(montgomery_ts$deaths_delta)

deaths_today_moco <- round(montgomery_ts$deaths_delta_ma[nrow(montgomery_ts)],0)
deaths_last_week_moco <- montgomery_ts$deaths_delta_ma[nrow(montgomery_ts)-7]

perc_deaths_moco <- round(((deaths_today_moco - deaths_last_week_moco)/deaths_last_week_moco),3)*100
deaths_text_moco <- paste(as.character(today()),"\n","___24 Hours___\nDeaths Today: +", as.character(deaths_today_moco), "\nPercent Change (7 Days): ", perc_change_txt(perc_deaths_moco), "%\nData Source: Johns Hopkins University CSSE")

mont_p2 <- montgomery_ts %>% ggplot() + 
    geom_rect(montgomery_ts, x=montgomery_ts$date, y = montgomery_ts$deaths_delta_ma, mapping = aes(xmin = lag(date), xmax = date, fill = deaths_dir), ymin = 0, ymax = Inf, alpha = 0.3) + 
    geom_point(aes(x = date, y = deaths_delta, color = ""), alpha = 0.7)+
    geom_line(aes(x = date, y = deaths_delta_ma, color = ""), size = 1.2, alpha = 0.9) +
    scale_fill_manual(values = c("red", "green"))+
    scale_color_manual(values = "black", "black")+
    labs(y = "", title = "Daily Deaths in Montgomery County", x = "Date") +
    theme(legend.position = "none") +
    pq + 
    ylim(0,max(montgomery_ts$deaths_delta))+
    annotate(geom = "text", x = xrange[1], y = yrange[2], label = paste("Note: 7 Day Moving Average", collapse = "\n"), hjust = 0, vjust = 1, size = 4)+jhu_caption+
    labs(caption=deaths_text_moco, vjust= 1)
mont_p2
```

Frederick County Data
```{r}
frederick_ts <- md_combined_ts %>% 
  filter(County == "Frederick") %>% 
  mutate(cases_dir = (cases_delta_ma <= lag(cases_delta_ma)), deaths_dir = (deaths_delta_ma <= lag(deaths_delta_ma))) %>% 
  filter(date %in% sinceMarch16)
  
```

```{r message=FALSE, warning=FALSE}
xrange <-range(frederick_ts$date)
yrange <- range(frederick_ts$cases_delta)

cases_today_fr <- round(frederick_ts$cases_delta_ma[nrow(frederick_ts)])
cases_last_week_fr <- frederick_ts$cases_delta_ma[nrow(frederick_ts)-7]

perc_change_fr <- round(((cases_today_fr - cases_last_week_fr)/cases_last_week_fr),3)*100
cases_text_fr <- paste(as.character(today()),"\n","___24 Hours___\nNew Cases: +", as.character(cases_today_fr), "\nPercent Change (7 Days): ", perc_change_txt(perc_change_fr), "%\nData Source: Johns Hopkins University CSSE")

fred_p1 <- frederick_ts %>% ggplot() + 
    geom_rect(frederick_ts, x=frederick_ts$date, y = frederick_ts$cases_delta, mapping = aes(xmin = lag(date), xmax = date, fill = cases_dir), ymin = 0, ymax = Inf, alpha = 0.3) + 
    geom_point(aes(x=date, y=cases_delta, color=""), alpha = 0.7)+  
    geom_line(aes(x = date, y = cases_delta_ma, color = ""), size = 1.2, alpha = 0.9) +
    scale_color_manual(values ="black", "black")+
    scale_fill_manual(values = c("blue", "yellow"))+
    labs(y = "", title = "Daily New Cases in Frederick County", x = "Date") +
    theme(legend.position = "none") +
    pq+
    ylim(0,max(frederick_ts$cases_delta))+
    annotate(geom = "text", x = xrange[1], y = yrange[2], label = paste("Note: 7 Day Moving Average", collapse = "\n"), hjust = 0, vjust = 1, size = 4)+jhu_caption+
    labs(caption=cases_text_fr, vjust= 1)
fred_p1
```

Percent Change in Deaths (5 Day Moving Average)
```{r warning = FALSE}
xrange <-range(frederick_ts$date)
yrange <- range(frederick_ts$deaths_delta)

deaths_today_fr <- round(frederick_ts$deaths_delta[nrow(frederick_ts)],0)
deaths_last_week_fr <- frederick_ts$deaths_delta_ma[nrow(frederick_ts)-7]

perc_deaths_fr <- round(((deaths_today_fr - deaths_last_week_fr)/deaths_last_week_fr),3)*100
deaths_text_fr <- paste(as.character(mdy(as.character(today()))),"\n","___24 Hours___\nDeaths Today: +", as.character(deaths_today_fr), "\nPercent Change (7 Days): ", perc_change_txt(perc_deaths_fr), "%\nData Source: Johns Hopkins University CSSE")

fred_p2 <- frederick_ts %>% ggplot() + 
    geom_rect(frederick_ts, x=frederick_ts$date, y = frederick_ts$deaths_delta_ma, mapping = aes(xmin = lag(date), xmax = date, fill = deaths_dir), ymin = 0, ymax = Inf, alpha = 0.3) + 
    geom_point(aes(x = date, y = deaths_delta), alpha = 0.7)+
    geom_line(aes(x = date, y = deaths_delta_ma), size = 1.2, alpha = 0.9) +
    scale_fill_manual(values = c("red", "green"))+
    #scale_color_manual(values = "black")+
    labs(y = "", title = "Daily Deaths in Frederick County", x = "Date") +
    theme(legend.position = "none", plot.tag = element_text(hjust = 0, vjust = 1, size = 12)) +
    pq + 
    ylim(0,max(frederick_ts$deaths_delta))+
    annotate(geom = "text", x = xrange[2], y = yrange[2], label = paste("Note: 7 Day Moving Average", collapse = "\n"), hjust = 1, vjust = 1, size = 4)+
    jhu_caption+
    labs(caption=deaths_text_fr, vjust= 1)

fred_p2

```
