---
title: "R Notebook"
output: html_notebook
---


```{r setup, include=FALSE}
library(tidyverse)
library(magrittr)
library(ggpubr)
library(lubridate)
#library(DescTools)
#library(effsize)
#library(pwr)
#library(lmerTest)
#library(sjPlot)
#library(webshot)

#library(readxl)
#library(elections)
library(caret)
#library(earth)
library(Formula)
library(plotrix)
library(plotmo)
library(RANN)
library(doParallel)
```

```{r}
sinceMarch16 <- seq(date("2020-06-03"), today()-1, by=1)
last30 <- seq(today()-30, today(), by=1)

bold.14.text <- element_text(face = "bold", size = 12)

pq <- theme(text = bold.14.text) +
  #theme(axis.ticks = element_blank()) +
  theme(panel.border = element_rect(colour = "black", fill=NA, size=2),
        panel.background=element_rect(colour = NA, fill = "white"))
jhu_caption <- labs(caption="Data Source: Johns Hopkins University CSSE")
```

Load Data
```{r}
ts_date_count <- today() - ymd(20200122)

confirmed_us_ts <- read_csv("../COVID-19/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_US.csv", 
                                 col_types=str_c('cccddcccddc', 
                                                 str_c(rep("i", times=ts_date_count), collapse=""))
                                 )

uid <- read_csv("../COVID-19/csse_covid_19_data/UID_ISO_FIPS_LookUp_Table.csv", col_types = "cccddcccddci")

mask_use <- read_csv("../election_night2020/context/covid/raw/mask-use-by-county.csv", col_names = c("FIPS","NEVER","RARELY","SOMETIMES","FREQUENTLY","ALWAYS"), col_types = "dddddd", skip=1)
election_results_raw <- read_csv("../election_night2020/results/leip_natl_data.csv")
summary(election_results_raw)
```
```{r}
election_results_clean <- election_results_raw %>% 
  pivot_longer(`Joseph R. Biden Jr.`:last_col(), names_to = "Candidate", values_to = "Votes")
election_ratios <- election_results_clean %>%
  mutate(Percent_Vote = case_when(
    `Total Vote` == 0 ~ 0,
    Votes == 0 ~ 0,
    TRUE ~ 100*Votes/`Total Vote`
    )) %>% 
  filter(Candidate %in% c("Joseph R. Biden Jr.", "Donald J. Trump", "Dr. Jo Jorgensen")) %>% 
  group_by(FIPS) %>% 
  mutate(Winner = Candidate[Votes == max(Votes)]) %>% 
  mutate(Winner = case_when(
    (max(Votes) == 0) ~ "NA",
    (max(Votes) > 0) ~ Winner
    )) %>% 
  ungroup() %>% 
  filter(Winner != "NA") %>% 
  select(FIPS, `Geographic Name`, `Geographic Subtype`, Winner, `Total Vote`, Candidate, Votes, Percent_Vote) %>% 
  pivot_wider(id_cols=FIPS:`Total Vote`, names_from = "Candidate", values_from = "Percent_Vote") %>% 
  #mutate(`Donald J. Trump` = cut(`Donald J. Trump`, breaks = c(-Inf, seq(5, 100, by = 5)), labels = c(paste(seq(5,100,by=5), rep("%"))))) %>% 
  rename(Admin2 = `Geographic Name`)
```

```{r}
clean_uid <- uid %>% 
  select(-iso2, -code3, -Lat, -Long_) %>% 
  arrange(UID)
```


```{r}
#matches("`(1?[0-9]{1})/([0-2]?[0-9]{1}/20)`")

cases_ts <- confirmed_us_ts %>%
  filter(!(Province_State %in% c("Diamond Princess", "Recovered", "Grand Princess"))) %>%
  select(-iso2, -code3, -Lat, -Long_) %>% 
  #filter(State_Province = "Alabama") %>% 
  arrange(UID) %>% 
  # pivot data to make dates a new column
  pivot_longer(`1/22/20`:last_col(), names_to = "date", values_to = "cases") %>%
  # join with uid table to acquire the population
  mutate(date=mdy(date)) %>% 
  left_join(clean_uid, by=c("UID", "iso3", "FIPS","Admin2", "Province_State", "Country_Region", "Combined_Key")) %>% 
  filter(Admin2 != 'Unassigned') %>% 
  filter(!(str_starts(Admin2, "Out of"))) %>% 
  arrange(Province_State, Admin2) %>% 
  group_by(UID) %>% 
  arrange(date) %>% 
  filter(date %in% sinceMarch16) %>% 
  mutate(cases = cases-min(cases)) %>% 
  mutate(cases_per_100k = 10e4 * cases / Population, perc_change = 100*(cases_per_100k-lag(cases_per_100k,1))/ lag(cases_per_100k,1)) %>% 
  ungroup()

cases_ts$perc_change[is.infinite(cases_ts$perc_change)] <- 100

cases_ts %<>% 
  filter(cases > 5, perc_change > 2) %>%  
  arrange(Province_State, Admin2, date)

cases_ts
#cases_ts$perc_change[is.na(cases_ts$perc_change)] <- 0


cases_ts_sum <- cases_ts %>% 
  group_by(FIPS) %>% 
  #filter(perc_change>200) %>% 
  summarise(max_case_rate = max(cases_per_100k), max_change = max(perc_change), avg = mean(perc_change)) %>%
  ungroup() %>% 
  left_join(clean_uid, by="FIPS") %>% 
  select(FIPS, Combined_Key, max_case_rate, max_change, avg)
  
  
```


```{r, echo = FALSE}
cases_votes <- cases_ts %>% 
  filter(date == max(date)) %>% 
  filter(Province_State != "Alaska") %>% 
  inner_join(election_ratios, by = c("FIPS")) %>% 
  select(-`Geographic Subtype`, -date) %>% 
  inner_join(mask_use, by = "FIPS") %>% 
  mutate(Winner = factor(Winner)) %>% 
  mutate(score = (1.5*ALWAYS + FREQUENTLY) - (SOMETIMES + RARELY + 1.5*NEVER))
cases_votes_sum <- cases_ts_sum %>% 
  inner_join(election_ratios, by=c("FIPS")) %>% 
  inner_join(clean_uid, by=c("FIPS","Admin2", "Combined_Key")) %>% 
  inner_join(mask_use, by = "FIPS") %>% 
  mutate(Winner = factor(Winner)) %>% 
  mutate(score = (1.5*ALWAYS + FREQUENTLY) - (SOMETIMES + RARELY + 1.5*NEVER))
  

summary(cases_votes_sum)

```
```{r}
summary(lm(cases_per_100k ~ score, data=cases_votes))

ggscatter(cases_votes, y="cases_per_100k", x=c("score", "NEVER", "ALWAYS"), add="reg.line", cor.coef = T)
ggscatter(cases_votes, y="Donald J. Trump", x=c("score", "NEVER", "ALWAYS"), add="reg.line", cor.coef = T)
#ggscatter(cases_votes_sum[sample(1:nrow(cases_votes_sum),50, replace=FALSE),], x="NEVER", y="avg", color="Donald J. Trump", size="Donald J. Trump")
```

```{r}
training_data <- cases_votes_sum %>% 
  select(max_case_rate, max_change, avg, ALWAYS, NEVER, `Donald J. Trump`)# %>% #NEVER, ALWAYS, Winner) %>% 
  #mutate(Winner = fct_recode(Winner, Trump='Donald J. Trump', Biden='Joseph R. Biden Jr.'))

set.seed(100)

validation_index <- createDataPartition(training_data$`Donald J. Trump`, p=0.80, list=FALSE)
validation <- training_data[-validation_index,]
training_data <- training_data[validation_index,]
summary(training_data)


```

```{r}
preProcess_missingdata_model <- preProcess(training_data, method = 'medianImpute')
training_data <- predict(preProcess_missingdata_model, newdata=training_data)
```


Dummy models
```{r, eval=FALSE}

dummies_model <- dummyVars(`Donald J. Trump` ~ ., data=training_data)
trainData_mat <- predict(dummies_model, newdata = training_data)
training_data <- data.frame(trainData_mat)
```

Data Preprocessing
```{r}
#preProcess_range_model <- preProcess(training_data, method="range", rangeBounds = c(0,1))
#training_data <- predict(preProcess_range_model, newdata=training_data)

xvar <- training_data[,1:5]
yvar <- training_data$`Donald J. Trump`

training_data$`Donald J. Trump` <- yvar
training_data
apply(training_data[,1:6], 2, FUN=function(x){c('min'=min(x), 'max'=max(x))})
```
```{r}
modelLookup("rf")
```
```{r}


#png("feature_plot_masks.png", width=900, height=900, units = 'px')
#featurePlot(x=xvar[4:5], y=yvar, plot="ellipse")
#dev.off()

png("feature_plot_cases.png", width=900, height=900, units = 'px')
featurePlot(x=xvar[1:3], y=yvar, plot="ellipse")
dev.off()

test_data <- predict(preProcess_missingdata_model, newdata = validation)
test_data2 <- test_data#predict(preProcess_range_model, newdata=test_data)
apply(test_data[,1:6], 2, FUN=function(x){c('min'=min(x), 'max'=max(x))})
apply(test_data2[,1:6], 2, FUN=function(x){c('min'=min(x), 'max'=max(x))})
```

```{r, eval=FALSE}
set.seed(100)
registerDoSEQ()
model_luna <- train(`Donald J. Trump` ~ ., data = training_data, method = 'earth')
fitted <- predict(model_luna)
model_luna

```

Prepare and Run Tests
```{r, eval=FALSE}


head(test_data2)

predicted <- predict(model_luna, test_data2)
head(predicted)
```

```{r, eval=FALSE}
confusionMatrix(reference=test_data$`Donald J. Trump`, data = predicted, mode = "everything", positive = "Trump")
```
```{r}
registerDoSEQ()
# Define the training control
fitControl <- trainControl(
    method = 'cv',                   # k-fold cross validation
    number = 20,                      # number of folds
    savePredictions = 'final',       # saves predictions for optimal tuning parameter
    #classProbs = T,                  # should class probabilities be returned
    summaryFunction=defaultSummary  # results summary function
) 
# Step 1: Tune hyper parameters by setting tuneLength
set.seed(100)
model_luna2 <- train(`Donald J. Trump` ~ ., data = training_data, method = 'lm', tuneLength = 5, trControl = fitControl)
model_luna2
```

```{r}
# Step 2: Predict on testData and Compute the confusion matrix
predicted <- predict(model_luna2, test_data2)
#confusionMatrix(reference = validation$`Donald J. Trump`, data = predicted, mode='everything', positive='Trump')
model <- data.frame(index = seq(1:length(predicted)), y = predicted, actual = test_data2$`Donald J. Trump`) %>% pivot_longer(y:actual, names_to = "category", values_to = "trump_vote")
ggscatter(model, x="index", y="trump_vote", color="category")
```

```{r}
varimp_mars <- varImp(model_luna2)
plot(varimp_mars)
```

```{r}
set.seed(100)

cl <- makePSOCKcluster(2)
registerDoParallel(cl)
#registerDoSEQ()

model_adaboost <- train(`Donald J. Trump` ~ ., data = training_data, method = 'bridge', tuneLength = 10, trControl = fitControl)
stopCluster(cl)
model_adaboost
```

```{r}
predicted2 <- predict(model_adaboost, test_data2)
#confusionMatrix(reference = validation$`Donald J. Trump`, data = predicted2, mode="everything", positive = "Trump")
```

```{r}
cl <- makePSOCKcluster(2)
registerDoParallel(cl)
set.seed(100)
model_rf <- train(`Donald J. Trump` ~ ., data = training_data, method = 'rf', tuneLength = 4, trControl = fitControl)
stopCluster(cl)
model_rf
```
```{r, eval=FALSE}
predicted4 <- predict(model_rf, test_data2)
confusionMatrix(reference = validation$`Donald J. Trump`, data = predicted4, mode="everything", positive = "Trump")
```





```{r, eval = TRUE}
set.seed(100)
gbmGrid <- expand.grid(interaction.depth = c(1,5,9), 
                       n.trees = (1:30)*50,
                       shrinkage=0.1,
                       n.minobsinnode=20)

cl <- makePSOCKcluster(2)
registerDoParallel(cl)
model_xgbDART <- train(`Donald J. Trump` ~ ., data = training_data, method = 'gbm', tuneGrid = gbmGrid, trControl = fitControl)#, metric="Accuracy")
stopCluster(cl)
model_xgbDART
```

```{r}
trellis.par.set(caretTheme())
plot(model_xgbDART)
```

```{r, eval=FALSE}
predicted3 <- predict(model_xgbDART, newdata=test_data2)
test_data3 <- test_data2 %>% mutate(index = seq(1:length(`Donald J. Trump`)))
model_3 <- data.frame(index = seq(1:length(predicted3)), prediction = predicted3, actual = test_data2$`Donald J. Trump`) %>% pivot_longer(prediction:actual, names_to = "category", values_to = "trump_vote") %>% inner_join(test_data3, by="index")
t.test(trump_vote ~ category, data = model_3, paired=T, alternative= "greater")
#confusionMatrix(reference=validation$`Donald J. Trump`, data = predicted3, mode='everything', positive='Trump')
ggscatter(sample(model_3), x=c("NEVER","ALWAYS", "max_case_rate", "max_change", "avg"), y="trump_vote", color="category", facet.by = "category")#, add="reg.line", cor.coef=T)
```


```{r, eval=FALSE}
model_3 <- data.frame(prediction = predicted3, actual = validation$`Donald J. Trump`)# %>% pivot_longer(prediction:actual, names_to = "category", values_to = "`Donald J. Trump`") %>% group_by(category, `Donald J. Trump`) %>% summarize(frequency = n())
data.frame(index = seq(1:length(predicted)), y = predicted3, actual = test_data2$`Donald J. Trump`) %>% pivot_longer(y:actual, names_to = "category", values_to = "trump_vote")


#chisq_table <- model_3 %>% group_by(`Donald J. Trump`) %>% pivot_wider(names_from = "category", values_from = "frequency")
#chisq_table2 <- data.frame(prediction = chisq_table$prediction, actual = chisq_table$actual)
#fisher.test(chisq_table2)
```


